### ISSUE TITLE
Issue with Ionic state restore

### ISSUE THREAD

**Issue by Juljan** [obetomuniz/ionic-google-maps-starter#14]
Hello,

This is my first Ionic project so it may be a dumb question (sorry). 

When following the readme, I get stuck at the command `ionic state restore` whose output is : 

```
[ERROR] Unable to find command: state restore
        You may need to be in an Ionic project directory.
```

What's wrong ? Do I have to type something to init the project first ? 

ionic infos tells : 

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

System:

    Node       : v6.3.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed


```

**Comment by ulukai-ork** [comment]
The command seems to have been deleted.

Maybe you should try using `ionic cordova platform rm android` and then `ionic cordova platform add android` (or `ios` if you're developing for iPhone)

It will delete platform and reinstall platform with its cordova native plugins. `ionic state restore` or `ionic state reset` were only reinstalling plugins without deleting the whole platform.. But since all the content of the platforms folder is (should be) generated.. It will do the same.

**Comment by obetomuniz** [comment]
Closing this issue because I'm deprecating this Ionic Starter.
